### ISSUE TITLE
Throat.area and Throat.perimeter calculation

### ISSUE THREAD

**Issue by Artshap** [PMEAL/OpenPNM#1334] opened 2019-11-05 01:38 UTC
[example.zip](https://github.com/PMEAL/OpenPNM/files/3806912/example.zip)

Dear development team,

I am using porespy to create a pore network and export it to csv using openpnm. When I have exported it I noticed that values for throat area and perimeter are strange and although the source codes are straightforward, they do not match the manual calculation. I am not sure if I should use the provided values for calculating the shape factor or re-calculate area and perimeter myself.

I was under the assumption that porespy generated network throats are all cylinders for throats and spheres for pores. 

Could you please let me know what is the underlying calculation there or if I am wrong somewhere? 

Screenshot from excel is below.

![openpnm](https://user-images.githubusercontent.com/49969695/68171749-25d90600-ffc9-11e9-9224-54136cfed08a.png)

**Comment by lanetszb** [comment] 2019-11-15 04:41
Hi all,

I've also encountered this type of problem. The manual calculation of throat diameters (pi*r**2) would not match the value exported from openPNM ('throat.area'). I would be grateful if you address this issue.

Looking forward to hearing from you.

Kind regards, Zak

**Comment by jgostick** [comment] 2019-11-15 15:05
Hi @lanetszb and @Artshap 
Sorry for the slow reply to this.   @Zohaib-Atiq can you take a look into this?

**Comment by Zohaib-Atiq** [comment] 2019-11-15 15:57
Hi @lanetszb and @Artshap
Are you extracting irregular shape pores or regular spherical pores and cylindrical throats?

Zohaib

**Comment by jgostick** [comment] 2019-11-16 04:40
I have tried to reproduce the problem, and I'm not seeing anything strange.  I print the dict returned by PoreSpy's ``regions_to_network`` function, and then load this into an OpenPNM network, then print it, I get exactly the same values for throat.area.  This isn't a surprize since this is literally just transferring data from one object to another.  I think I'll either @Artshap or @lanetszb to send me a script that reproduces this error.

**Comment by Artshap** [comment] 2019-11-17 02:54
@jgostick @Zohaib-Atiq thank you for your replies!

I may have not phrased the problem correctly. This issue is not with inconsistent values between OpenPNM and PoreSpy. The issue is with reproducing the calculation manually, which I was not able to do by using standard equations.

I have looked again into the paper about PoreSpy and found the description of how throat perimeter is calculated there (based on the number of voxels). Which explains why the calculation might not be matching. I assume area of the throat is calculated in the same manner? If yes, the issue is closed then. And it turns out I should have posted this in PoreSpy. 

I was initially confused by wording in the paper:
"It should be stressed that the following interpretation of pore and throat size information represents only the most general approach", which I at first assumed was finding the throat diameter and calculating area and perimeter from it's value using equations for cylinder and circle, since there are functions for that those equations in OpenPNM.

**Comment by jgostick** [comment] 2019-11-17 03:30
Hi @Artshap, yes, the quote you pulled from the paper is very astute.  We have actually been discussing lately about how it might be time to improve the geometric values extracted for things like this. In fact, we have already added an argument to the ``networks.snow`` method, called ``marching_cubes_area``, which if True will use the marching cubes to get surface and interaction areas, rather than counting cubes.  It's slower, so we turn if off by default, but it's pretty accurate.

**Closed by jgostick** 2019-11-17 03:30 UTC
