### ISSUE TITLE
Minor bug in the RelativePermeability.py

### ISSUE THREAD

**Issue by saeedtelvari** [PMEAL/OpenPNM#2049] opened 2021-10-14 09:33 UTC
In the __RelativePermeability.py__ in the metrics folder, settings are initialized with 'flow_inlet' and 'flow_outlet'.
But in the rest of the program, it is written as 'flow_inlet**s**' and 'flow_outlet**s**', causing the following error:

![Screenshot 2021-10-14 125359](https://user-images.githubusercontent.com/65657109/137290704-8a4621b5-c558-4d28-a70b-f986c3bfd4a9.jpg)

**Comment by Ni2M** [comment] 2021-11-08 21:25
Hi. The settings inlets/outlets will be fixed in our next release. However, I believe this is not the cause of that error, as the algorithm automatically assigns the inlets/outlets for a 2D or 3D network (https://github.com/PMEAL/OpenPNM/blob/bc228c59e60376dd59fef4ecd505d13de67241e7/openpnm/algorithms/metrics/RelativePermeability.py#L70 and https://github.com/PMEAL/OpenPNM/blob/bc228c59e60376dd59fef4ecd505d13de67241e7/openpnm/algorithms/metrics/RelativePermeability.py#L86.  Since the last release we have changed the RelativePermeability.py on dev branch and its example, accordingly. This branch will be released next time. I believe you are using the last release of OpenPNM (or release branch) while using the settings syntax that works only on dev branch. If so, please see the relperm example that is associated with the release version. It can be found on [release branch on github](https://github.com/PMEAL/OpenPNM/blob/release/examples/notebooks/algorithms/multiphase/relative_permeability_metrics.ipynb). Based on the example the settings line above should be replaced by ```rp.setup(invading_phase='co2', defending_phase='water',
         invasion_sequence='invasion_sequence')```. Please see https://github.com/PMEAL/OpenPNM/discussions/2050 for more details on a similar error.

**Comment by jgostick** [comment] 2021-11-10 16:34
we are going to remove this RelativePermeability metrics class in V3.0.  The algorithm is a bit too complex with too many subtleties to be packaged in a 'black box' metrics algorithm.  We will take the code in the old class and convert it to a set of examples in the docs so people can see how to compute these curves themselves, along with plenty of commentary on the mentioned subtleties.

**Closed as completed by jgostick** 2021-11-10 16:34 UTC
Labels: bug
