### ISSUE TITLE
Raise exception if no pores/throats are passed to Geometry

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1784] opened 2020-11-23 15:02 UTC
This is similar to #1709

**Comment by jgostick** [comment] 2020-11-23 15:13
Ya, but in principle it is OK to create a geometry with no pores or throats.  We (or rather I) changed this a few months ago because defaulting to ALL pores and throats was a strange gotcha.  

Perhaps the best compromise would be for pores and throats to be mandatory arguments, and you have to pass something.  So:

```
geo = op.geometry.StickAndBall(network=pn, pores=None, throats=None)  # Option 1
geo = op.geometry.StickAndBall(network=pn, pores=[], throats=[])  # Option 2
```

Not sure how this will play with the PNM format, which was the main motivation for this change in the first place.

**Comment by ma-sadeghi** [comment] 2020-11-23 17:55
You're right. I think making `pores` and `throats` mandatory arguments is probably a good idea, unless we can come up with a scenario where we want an empty `Geometry` (or an initially-empty one, but later-to-be-filled)

**Comment by jgostick** [comment] 2020-12-03 05:24
I have confirmed that the PNM format does not need the geometry to have empty instantiation.  SOOO, it's possible to got back to the old way, where ``op.geometry.StickAndBall(network=pn)`` automatically applies to all pores and throats.  I'm just not sure that we should do this.  I closed off this behavior because it was a hidden gotcha.   I'm not sure why we want to do it again?

**Comment by jgostick** [comment] 2020-12-05 00:35
We now raise an exception at the algorithm level is not pores/throats are defined, so this is fixed in a round-about way

**Comment by ma-sadeghi** [comment] 2021-01-26 21:13
I just noticed that this's not yet been fixed.

**Comment by jgostick** [comment] 2021-02-01 16:20
We are adding this to to ``_check_special`` method

**Closed as completed** 2021-02-16 16:22 UTC
Labels: enhancement
