### ISSUE TITLE
Extend network after geometries are created

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#312] opened 2015-03-11 11:34 UTC
I noticed this is a "to do" in the extend method in GenericNetwork. It would be useful to me right now as I've just created a bunch of networks but now need to add some boundaries as something went wrong with the geometry class I used for them and they got deleted. I can give it a crack but may need some guidance on how all the objects are linked up and talk to each other. Alternatively, is there a clean way around this? For example copy network, remove geometries from original, add boundaries, generate empty geometries with correct class, copy data back in. My issue is I don't want to regenerate all my networks as it took 3 days to generate them all.

**Comment by TomTranter** [comment] 2015-03-11 13:05
I've managed to do the work-around by copying props and private attributes individually. It didn't like copying the whole object

**Comment by jgostick** [comment] 2015-03-11 14:27
The trouble with extending after the fact is that you have to put nan's everywhere for all the new properties.  As long as we're ok with this, then it should be pretty easy.

**Comment by TomTranter** [comment] 2015-03-11 14:40
Which object are you referring to. if you have a network and geometries only then adding pores to the network then assigning them to a new geometry wouldn't result in nans unless certain properties are in one geom and not others but this happens anyway. If you have run algorithms then you'd need to fill with nans but chances are you'll need to re-run the algorithms anyway. I see network and geometry as permanent data I want to save and use over but phase and algorithm data is temporary

**Comment by jgostick** [comment] 2015-03-16 17:53
I was mistaken to say 'nans'  The problem is that the new pores/throats will need to be assigned to geometry and physics objects, so any 'extends' will actually break the simulation until these pores/throats have a home.  I'm sure there is a behind-the-scenes workaround, but I hesitate to allow the 'official' extend method to do this.

**Comment by TomTranter** [comment] 2015-03-18 17:40
new branch issue_312 ready for testing.

**Comment by jgostick** [comment] 2015-03-23 04:25
I've pushed a few commits to the branch started by @TomTranter .  The code generally works with one problem...as I said above, when you add pores to an object you end up with the question of which values to put into the new locations...i.e. adding nans.  IF all of the properties on the object are generated by models, then there is no problem, you just have to regenerate the object.  If any of the properties are not models, however, you have no way of knowing what values to put into the new locations.   I don't know of any way around this at the moment.  So, bottom line, you can add/remove pores from objects, but in most cases this will break things related to the property arrays.

**Comment by jgostick** [comment] 2015-03-28 18:44
This PR has been merged

**Closed by jgostick** 2015-03-28 18:44 UTC
Labels: enhancement, question
