### ISSUE TITLE
OpenPNM PoreSpy IO is no longer compatible with the dev version of PoreSpy

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2777] opened 2023-06-21 18:49 UTC
`openpnm.io.network_from_porespy` expects either a dict, or a path, but `snow2` now returns a `Results` object, which contains the network.

**Comment by jgostick** [comment] 2023-08-24 03:21
This is a dupe of #2665

**Closed as completed by jgostick** 2023-08-24 03:21 UTC
Labels: bug
