### ISSUE TITLE
Problem with passing second physics to PNP

### ISSUE THREAD

**Issue by Ni2M** [PMEAL/OpenPNM#1485] opened 2020-05-20 21:03 UTC
Hi @magnaou  I'm having problem with using PNP algorithm, when I am trying to pass the second physics to the PNP algorithm. I tried to change line 127 https://github.com/PMEAL/OpenPNM/blob/1546fa1ac2204443bde916f2037fac383c5069ae/openpnm/algorithms/NernstPlanckMultiphysics.py#L127,  and https://github.com/PMEAL/OpenPNM/blob/1546fa1ac2204443bde916f2037fac383c5069ae/openpnm/algorithms/NernstPlanckMultiphysics.py#L136, but it still needs changing the  line https://github.com/PMEAL/OpenPNM/blob/1546fa1ac2204443bde916f2037fac383c5069ae/openpnm/algorithms/NernstPlanckMultiphysics.py#L96 in a way that algorithm still works. I was worried about changing the consistency of the algorithm so I didn't try any more. I highly appreciate it, if you could please review this problem.

**Comment by jgostick** [comment] 2020-05-21 03:08
This is a duplicate of #1481

**Closed as completed** 2020-06-08 05:12 UTC
Labels: bug
