### ISSUE TITLE
Add an optional mass transfer resistance between pore centers and walls

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1765] opened 2020-11-19 20:03 UTC

**Comment by ma-sadeghi** [comment] 2020-11-20 02:38
Possible duplicate of #1454

**Comment by jgostick** [comment] 2020-11-20 04:12
Yes, dupe for sure.  But this has now become more urgent.  We should reopen that other issue, and get thinking about this.

**Closed as completed** 2020-11-22 22:08 UTC
