### ISSUE TITLE
add_boundaries after stitching

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#484] opened 2016-01-19 11:11 UTC
Say we have two cubic networks of shape [5,5,5] and equal lattice spacing we want to stitch together one on top of the other in the z-direction. If we want to add_boundary pores then we can run the add_boundary method on each network then trim the top_boundary from pn1 and the bottom_boundary from pn2 and stitch them after translating the pn2 coordinates. The alternative, one would have thought, would be to stitch them and then run the add_boundaries method on the larger network. However, the add_boundaries method uses a private attribute of the original network (the shape) to determine where to put the new pores and this is not updated to reflect the shape of the new cubic network. So a plane of boundary pores is in fact created through the middle of the network. I propose we either prevent the user from adding boundaries after a stitch or update the method to reflect the new shape. This would be potentially tricky after stitching networks of different shapes or with different lattice spacing, but also quite useful.

**Comment by jgostick** [comment] 2016-01-19 15:23
We've added a new method to Cubic called add_boundary_pores, which requires you specify which pores to add boundaries to.  You'd run this 6 time on a cube to get all six faces.  This is more cumbersome than the add_boundaries, but is foolproof and was intended to fix the problem you mention.  

We 'could' make add_boundaries more useful though.  @maghighi has a way to find surface pores (using the weighted vectors of throats) so we could use that logic to find all surface pores, then create boundary pores attached to these, then offset them.  The tricky part is the edge and corner pores.

**Comment by TomTranter** [comment] 2016-01-19 16:40
A general algorithm would identify surface pores and offset by a fixed amount in the surface normal direction. This would work for both cubic and Delaunay (with a few tweaks). I'm not sure what you mean by weighted vectors of throats but I would have thought using the upper and lower bounds of the pore coordinates would work. Corner pores would be automatically picked up if you cycled through the x,y,z upper and lower coordinates identifying pores that sit on that plane.

**Comment by jgostick** [comment] 2016-01-19 17:05
If you calculate the vector between a pore and each neighbor, and then add
the vectors, if a cubic pore has 6 neighbors its cumulative vector would be
0, if it's on a surface its cumulative vector points inward.

**Comment by TomTranter** [comment] 2016-01-20 11:22
It's a neat method but like you say it doesn't work for edges or corners or after throats have been trimmed or for Delaunay networks. Having looked at it again, there's quite a lot of Delaunay specific logic in the add boundaries method so I'm not sure a generic add_boundaries for all network types would work after all but the principle of using the min and max of the pore coords should work as long as the networks you're stitching together span the same distance, which they won't if the lattice spacing is different... you could do it one plane at a time and find the outer pores.

**Comment by jgostick** [comment] 2016-02-29 03:38
Since the add_boundary_pores methods addresses @TomTranter 's initial concern I'm going to close this issue.  I will, however, create a new issue about adding a 'find_surface_pores' function of the Utilities.topology tools class.

**Closed by jgostick** 2016-02-29 03:38 UTC
Labels: enhancement, Priority - Low
