### ISSUE TITLE
[Bug]: Turn off the cache when using the PNP or non Newtonian algs

### ISSUE THREAD

**Issue by magnaou** [PMEAL/OpenPNM#1589] opened 2020-07-20 18:32 UTC
Set {'cache_A': False, 'cache_b': False} in the PNP and non Newtonian algs.

**Comment by ma-sadeghi** [comment] 2020-07-23 14:13
@magnaou As per our discussion on Teams, this is not a bug on our algorithms' side, but is rather related to our dependency handling. So, we should always keep `cache_A` and `cache_b` as `True`. But, let's keep this issue as a reminder to fix the dependency handling bug.

**Comment by ma-sadeghi** [comment] 2020-08-12 01:05
@magnaou I just checked and it seems that the problem is fixed on the `dev` branch, meaning that the dependency handler automatically sets `cache_A` and `cache_b` to `False`, at least for `NonNewtonianStokesFlow`. Can you please confirm if that's indeed the case (both for NonNewtonian and NP)?

**Closed as completed** 2020-08-14 16:05 UTC
Labels: bug
