### ISSUE TITLE
'find_neighbor_pores' alters the results of 'find_connecting_pores' and 'find_connecting_throat'

### ISSUE THREAD

**Issue by raymond-guan1** [PMEAL/OpenPNM#1546] opened 2020-06-29 17:30 UTC
Using the 'find_neighbor_pores' appears to be affecting the connectivity of the network. When I run the code-block below, the value of the queried_throat and the output_throat are both equal to 1, which makes sense. However, when the 'find_neighbor_pores' line is uncommented, output_throat is now equal to 900.

```python
import openpnm as op

pn = op.network.Cubic(shape=[10, 10, 10], spacing=1e-4)
# pn.find_neighbor_pores(1)
queried_throat = 1
connected_pores = pn.find_connected_pores(queried_throat)
output_throat = pn.find_connecting_throat(connected_pores[0][0],connected_pores[0][1])
print('Original Throat: {}, Output Throat: {}'.format(queried_throat, output_throat[0]))
```

This issue extends to the 'find_connecting_throat' function. The code-block below correctly returns out_pores = [7, 8] in the code below. Uncommenting the 'find_neighbor_pores' line results in output_pores = [1, 2].

```python
import openpnm as op

pn = op.network.Cubic(shape=[10, 10, 10], spacing=1e-4)
#pn.find_neighbor_pores(1)
queried_pores = [7,8]
connecting_throat = pn.find_connecting_throat(queried_pores[0], queried_pores[1])
output_pores = pn.find_connected_pores(connecting_throat)
print('Input Pores: {}, Output Pores: {}'.format(queried_pores,output_pores))
```

**Comment by jgostick** [comment] 2020-06-29 17:39
Hmm, I can reproduce this, so I will investigate.  I will just note that the throat.conns array is stable throughout the above code, s the error is probably a cached version of the lil array changing for some reason.  

BTW, what version of scipy are you using?

**Comment by raymond-guan1** [comment] 2020-06-29 17:41
I am on 1.4.1!

**Comment by jgostick** [comment] 2020-07-01 03:49
Ok, I found the bug.  We cache some adjancency and incidence matrices to speed things up for later use.  This part is fine.  However, we also did a conversion between cached formats if one format was available but a different one was requested.  This was not working correctly due to some nuances in the scipy.sparse library.  I have removed this code block so if a version is not found in the cache a fresh one is created....which is probably just as fast as the conversion was anyway.  This will be merged into the main code tomorrow as a 'hotfix' in PR #1550 using our new autodeploy functionality, so I'm going to close this issue.

**Closed as completed** 2020-07-01 20:31 UTC
